# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{peach}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ben Hughes}]
  s.date = %q{2011-05-22}
  s.description = %q{Parallel Each and other parallel things}
  s.email = %q{ben@pixelmachine.org}
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "bn/peach_bn.rb",
    "bn/peach_test.rb",
    "lib/peach.rb",
    "peach.gemspec",
    "test/peach_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://peach.rubyforge.org}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.3}
  s.summary = %q{Parallel Each and other parallel things}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

